version: "3.8"
services:
  pleo-antaeus:
    build: .
    image: pleo-anteus:pleo-anteus
    ports:
      - "7000:7000"
    volumes:
      - pleo-antaeus-build-cache:/root/.gradle
    tty: true
    stdin_open: true # interactive
  scheduler:
    build:
      dockerfile: $PWD/pleo-antaeus-scheduler/Dockerfile
      context: $PWD/pleo-antaeus-scheduler
    image: pleo-antaeus-scheduler:pleo-anteus
volumes:
  pleo-antaeus-build-cache:
